"""crear tabla historias

Revision ID: 869926e4b171
Revises: fda96ab5c85e
Create Date: 2026-08-14 22:07:33.173581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869926e4b171'
down_revision = 'fda96ab5c85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('idioma', sa.String(length=2), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historias')
    # ### end Alembic commands ###
