"""agregar es_moderador, oculta y tabla reportes_historia

Revision ID: c5b23c329a5e
Revises: 9d38f0e5b717
Create Date: 2026-09-12 21:42:38.248706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b23c329a5e'
down_revision = '9d38f0e5b717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportes_historia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historia_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['historia_id'], ['historias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('historia_id', 'usuario_id', name='uq_reporte_historia_usuario')
    )
    with op.batch_alter_table('historias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oculta', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_moderador', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('es_moderador')

    with op.batch_alter_table('historias', schema=None) as batch_op:
        batch_op.drop_column('oculta')

    op.drop_table('reportes_historia')
    # ### end Alembic commands ###
