"""agregar disponibilidad de voluntarios y tabla sesiones

Revision ID: e41b5c7c5ff4
Revises: 869926e4b171
Create Date: 2026-08-15 23:37:27.646386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41b5c7c5ff4'
down_revision = '869926e4b171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_busca_id', sa.Integer(), nullable=False),
    sa.Column('usuario_voluntario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_busca_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_voluntario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disponible', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('disponible')

    op.drop_table('sesiones')
    # ### end Alembic commands ###
